# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Save api key
      env:
        USDS_KEY: ${{ secrets.USDS_KEY }}
      run: | 
        mkdir -p /home/runner/.local/share/flowsa/API_Keys/
        echo "$USDS_KEY" > /home/runner/.local/share/flowsa/API_Keys/USDA_Quickstats_API_KEY.txt
    - name: Test with pytest
      run: |
        pytest --doctest-modules
